plugins:
 - jekyll-remote-theme

title: Join the Distributed Denial of Secrets
description: DDoSecrets is the most important and active leak organization on the planet.
logo: logo.png
url: https://ddosecrets.com
locale: en_US

theme: jekyll-theme-cayman

sass:
  sass_dir:         assets/_sass
  style:            compressed


twitter: blue_leaks
