remote_theme: pages-themes/cayman@v0.2.0
plugins:
 - jekyll-remote-theme
title: DDoSecrets is Bringing Secrets to Light!



Distributed Denial of Secrets is the most important active leaking organization in the world. DDoSecrets has published over 250 datasets from more than 50 countries, adding up to nearly 100 terabytes. Our library reveals the inner workings of oligarchs' finances, fascist groups, shell companies, tax havens and banks as well as law enforcement, military, and political groups from all over the world.


Can you donate to support this important work?


While DDoSecrets' expenses have gone up, we remain an efficient, barebones operation. We are sometimes called a successor to WikiLeaks. For comparison, in 2010 WikiLeaks needed "€10,000 to €15,000 a month to maintain its Web presence," $200,000 a year to cover its operating expenses, and more than half a million dollars to pay a small staff. With a fraction of that budget, DDoSecrets is making more than 10,000 times the amount of data available.


This work comes with significant risk.


After we published BlueLeaks, a large cache of files from over 200 U.S. law enforcement agencies and intelligence fusion centers, German authorities seized the server for DDoSecrets' search system at the request of the FBI. The German prosecutor acted despite having no official paperwork and knowing DDoSecrets was a journalist group. At the same time, we were banned from social media. To this day, you can't Tweet any DDoSecrets.com web addresses.


We never bowed to pressure or stopped publishing. We debunked the U.S. Department of Homeland Security labeling us "criminal hackers." Despite the censorship, our library continues to impact public debate. The Parler videos we published were used as evidence during the second impeachment trial of President Donald Trump. 


Your contributions help us fight.


DDoSecrets can't do this work alone. We've partnered with groups like Harvard University's Institute for Quantitative Social Science, European Investigative Collaborations, the Henri-Nannen-Journalistenschule journalism school, and the Organized Crime and Corruption Reporting Project. During the Russo-Ukrainian War, we became known as one of the best public repositories for Russian files.


Although some of our data is available for search in a custom search engine, we want the Hunter Memorial Library back, to restore public access to the world's largest searchable archive of secrets. 


DDoSecrets has always been a global project. Accessibility for all languages in the archive has never been more important. We've completed the first translation of our website into Russian, and we want to add more languages.


We are just getting started.


By supporting DDoSecrets, you're supporting transparency efforts and journalism projects across the globe. Some highlights: 

    #29Leaks: Reporters from more than 20 outlets in 18 countries researched 10 years of records from Formations House, which created more than 400,000 shell companies for clients around the globe and are linked to fake banks, Iranian state oil companies, and the Italian mob.
    Chicago City Hall emails: We made tens of thousands of emails from Chicago's City Hall available, exposing the city's secret drone program funded with off-the-books cash.
    Fuerzas Represivas: The largest leak in history, co-published with Enlace Hacktivista: over 10 terabytes from police and military forces in Chile, Colombia, El Salvador, Mexico, and Peru. 
    Mining Secrets: 20 media outlets worked with data from the Swiss mining company Solway, exposing the environmental damages, efforts to bribe community leaders and police in Guatemala, and the surveillance of journalists.
    Myanmar financial data: Records of the financial motivations of the leaders of the military coup in Myanmar. The revelations pressure Western companies to cut funding to the dictatorship and cancel multi-million dollar projects in the region.
    Oath Keepers: We published internal emails and chat messages of the Oath Keepers, and distributed alleged membership lists to the group, exposing hundreds of elected officials, members of law enforcement and the military listed as members of the extremist militia. Oath Keepers members are currently on trial for their involvement in the January 6 coup attempt.
