plugins:
 - jekyll-remote-theme

title: DDoSecrets is Bringing Secrets to Light!
description: DDoSecrets is the most important and active leak organization on the planet.
url: https://ddosecrets.com
locale: en_US



sass:
  sass_dir:         assets/_sass
  style:            compressed
