plugins:
 - jekyll-remote-theme

title: Join the Distributed Denial of Secrets
description: DDoSecrets is the most important and active leak organization on the planet.
url: https://ddosecrets.charity
locale: en_US

theme: jekyll-theme-cayman

sass:
  sass_dir:         assets/_sass
  style:            compressed

twitter:
  username: blue_leaks
  card: summary_large_image

logo: assets/logo_transparent.png
