plugins:
 - jekyll-remote-theme

title: Help Distributed Denial of Secrets Leak!
description: DDoSecrets is the most important and active leak organization on the planet.
url: https://ddosecrets.com
locale: en_US

theme: jekyll-theme-cayman

sass:
  sass_dir:         assets/_sass
  style:            compressed
